# Framework Configuration

DomainName: 'apps.cloud.cit.cornell.edu'
Redirects:
  MAE 3270/4700/5700: 
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'citlabs-master-stack'

  INFO 4940:
    account:    '589868485103'
    region:     'us-east-1'
    stack:      'bi-pilot-prod'

ACM_ARN:    'arn:aws:acm:us-east-1:530735016655:certificate/eee571e2-c4cf-4205-b32b-c04a9ad4c338'
Bucket:     'cu-deng-appstream-framework'

VPC:        'vpc-d7408bb0'
RouteTables:
  -         'rtb-f5530692'
  -         'rtb-f7530690'

Tags:
  Application: 'appstream'
