# Framework Configuration

DomainName: 'apps.cloud.cit.cornell.edu'
Redirects:
  CIT Demo:
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'cit-demo-v2'

  MAE 1130: 
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'mae-production'

  MAE 2250: 
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'mae-production'

  MAE 3280: 
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'mae-production'

  MAE 4230/5230: 
    account:    '530735016655'
    region:     'us-east-1'
    stack:      'mae-production'

ACM_ARN:    'arn:aws:acm:us-east-1:530735016655:certificate/eee571e2-c4cf-4205-b32b-c04a9ad4c338'
Bucket:     'cu-deng-appstream-framework'

VPC:        'vpc-d7408bb0'
RouteTables:
  -         'rtb-f5530692'
  -         'rtb-f7530690'

Tags:
  Application: 'appstream'
